### ISSUE TITLE
Keine Darstellung der interaktiven Karte (teil 1, demo 01-john-snow)

### ISSUE THREAD

**Issue by ghost** [ganslats/TMF-School-2021-Block-7#1]
Guten Morgen,

bei der Ausführung des [John Snow Notebooks](https://github.com/ganslats/TMF-School-2021-Block-7/blob/main/Notebooks/teil-1-demo-01-john-snow.ipynb) in Binder wird die interaktive Karte nicht angezeigt. Getestet mit Firefox. 
Liegt dies an Binder?

![Bildschirmfoto 2021-06-24 um 10 57 07](https://user-images.githubusercontent.com/12896078/123234370-2e05f200-d4db-11eb-86b1-79b8ba4f6af3.png)

**Comment by ganslats** [comment]
Danke für den Hinweis! Ich habe das gerade im Vergleich mit Chrome, MS Edge und Firefox getestet und konnte das reproduzieren: auf Chrome & Edge läuft es problemlos, auf Firefox dagegen nicht. Der Firefox war in diesem Fall eine zentral von der Klinik-IT konfigurierte Version, so dass dort ggf. JavaScript deaktiviert sein könnte (ist für Leaflet erforderlich).
Können sie es mit einem anderen Browser oder ggf. Rechner (z.B. außerhalb Kliniknetz) probieren?

**Comment by ghost** [comment]
Danke für die Rückmeldung.
An sich ist handelt es sich um eine "ganz normale Firefox-Version" im privaten Homeoffice-Netz. 
Ich kann die Karte aber problemlos mit Safari erzeugen, sodass ich die restlichen Notebooks damit erstellen werde.
